<?php

namespace App\Helpers;

class Countries
{
    public static function all(): array
    {
        return [
            // Southeast Asia
            'BN' => ['flag' => '🇧🇳', 'name' => 'Brunei'],
            'KH' => ['flag' => '🇰🇭', 'name' => 'Cambodia'],
            'ID' => ['flag' => '🇮🇩', 'name' => 'Indonesia'],
            'LA' => ['flag' => '🇱🇦', 'name' => 'Laos'],
            'MY' => ['flag' => '🇲🇾', 'name' => 'Malaysia'],
            'MM' => ['flag' => '🇲🇲', 'name' => 'Myanmar'],
            'PH' => ['flag' => '🇵🇭', 'name' => 'Philippines'],
            'SG' => ['flag' => '🇸🇬', 'name' => 'Singapore'],
            'TH' => ['flag' => '🇹🇭', 'name' => 'Thailand'],
            'TL' => ['flag' => '🇹🇱', 'name' => 'Timor-Leste'],
            'VN' => ['flag' => '🇻🇳', 'name' => 'Vietnam'],
            // East Asia
            'CN' => ['flag' => '🇨🇳', 'name' => 'China'],
            'HK' => ['flag' => '🇭🇰', 'name' => 'Hong Kong'],
            'JP' => ['flag' => '🇯🇵', 'name' => 'Japan'],
            'MO' => ['flag' => '🇲🇴', 'name' => 'Macau'],
            'MN' => ['flag' => '🇲🇳', 'name' => 'Mongolia'],
            'KR' => ['flag' => '🇰🇷', 'name' => 'South Korea'],
            'TW' => ['flag' => '🇹🇼', 'name' => 'Taiwan'],
            // South Asia
            'BD' => ['flag' => '🇧🇩', 'name' => 'Bangladesh'],
            'BT' => ['flag' => '🇧🇹', 'name' => 'Bhutan'],
            'IN' => ['flag' => '🇮🇳', 'name' => 'India'],
            'MV' => ['flag' => '🇲🇻', 'name' => 'Maldives'],
            'NP' => ['flag' => '🇳🇵', 'name' => 'Nepal'],
            'PK' => ['flag' => '🇵🇰', 'name' => 'Pakistan'],
            'LK' => ['flag' => '🇱🇰', 'name' => 'Sri Lanka'],
            // Middle East
            'BH' => ['flag' => '🇧🇭', 'name' => 'Bahrain'],
            'EG' => ['flag' => '🇪🇬', 'name' => 'Egypt'],
            'IR' => ['flag' => '🇮🇷', 'name' => 'Iran'],
            'IQ' => ['flag' => '🇮🇶', 'name' => 'Iraq'],
            'IL' => ['flag' => '🇮🇱', 'name' => 'Israel'],
            'JO' => ['flag' => '🇯🇴', 'name' => 'Jordan'],
            'KW' => ['flag' => '🇰🇼', 'name' => 'Kuwait'],
            'LB' => ['flag' => '🇱🇧', 'name' => 'Lebanon'],
            'OM' => ['flag' => '🇴🇲', 'name' => 'Oman'],
            'QA' => ['flag' => '🇶🇦', 'name' => 'Qatar'],
            'SA' => ['flag' => '🇸🇦', 'name' => 'Saudi Arabia'],
            'SY' => ['flag' => '🇸🇾', 'name' => 'Syria'],
            'TR' => ['flag' => '🇹🇷', 'name' => 'Turkey'],
            'AE' => ['flag' => '🇦🇪', 'name' => 'UAE'],
            'YE' => ['flag' => '🇾🇪', 'name' => 'Yemen'],
            // Europe
            'AL' => ['flag' => '🇦🇱', 'name' => 'Albania'],
            'AD' => ['flag' => '🇦🇩', 'name' => 'Andorra'],
            'AT' => ['flag' => '🇦🇹', 'name' => 'Austria'],
            'BY' => ['flag' => '🇧🇾', 'name' => 'Belarus'],
            'BE' => ['flag' => '🇧🇪', 'name' => 'Belgium'],
            'BA' => ['flag' => '🇧🇦', 'name' => 'Bosnia'],
            'BG' => ['flag' => '🇧🇬', 'name' => 'Bulgaria'],
            'HR' => ['flag' => '🇭🇷', 'name' => 'Croatia'],
            'CY' => ['flag' => '🇨🇾', 'name' => 'Cyprus'],
            'CZ' => ['flag' => '🇨🇿', 'name' => 'Czech Republic'],
            'DK' => ['flag' => '🇩🇰', 'name' => 'Denmark'],
            'EE' => ['flag' => '🇪🇪', 'name' => 'Estonia'],
            'FI' => ['flag' => '🇫🇮', 'name' => 'Finland'],
            'FR' => ['flag' => '🇫🇷', 'name' => 'France'],
            'DE' => ['flag' => '🇩🇪', 'name' => 'Germany'],
            'GR' => ['flag' => '🇬🇷', 'name' => 'Greece'],
            'HU' => ['flag' => '🇭🇺', 'name' => 'Hungary'],
            'IS' => ['flag' => '🇮🇸', 'name' => 'Iceland'],
            'IE' => ['flag' => '🇮🇪', 'name' => 'Ireland'],
            'IT' => ['flag' => '🇮🇹', 'name' => 'Italy'],
            'LV' => ['flag' => '🇱🇻', 'name' => 'Latvia'],
            'LI' => ['flag' => '🇱🇮', 'name' => 'Liechtenstein'],
            'LT' => ['flag' => '🇱🇹', 'name' => 'Lithuania'],
            'LU' => ['flag' => '🇱🇺', 'name' => 'Luxembourg'],
            'MT' => ['flag' => '🇲🇹', 'name' => 'Malta'],
            'MD' => ['flag' => '🇲🇩', 'name' => 'Moldova'],
            'MC' => ['flag' => '🇲🇨', 'name' => 'Monaco'],
            'ME' => ['flag' => '🇲🇪', 'name' => 'Montenegro'],
            'NL' => ['flag' => '🇳🇱', 'name' => 'Netherlands'],
            'MK' => ['flag' => '🇲🇰', 'name' => 'North Macedonia'],
            'NO' => ['flag' => '🇳🇴', 'name' => 'Norway'],
            'PL' => ['flag' => '🇵🇱', 'name' => 'Poland'],
            'PT' => ['flag' => '🇵🇹', 'name' => 'Portugal'],
            'RO' => ['flag' => '🇷🇴', 'name' => 'Romania'],
            'RU' => ['flag' => '🇷🇺', 'name' => 'Russia'],
            'SM' => ['flag' => '🇸🇲', 'name' => 'San Marino'],
            'RS' => ['flag' => '🇷🇸', 'name' => 'Serbia'],
            'SK' => ['flag' => '🇸🇰', 'name' => 'Slovakia'],
            'SI' => ['flag' => '🇸🇮', 'name' => 'Slovenia'],
            'ES' => ['flag' => '🇪🇸', 'name' => 'Spain'],
            'SE' => ['flag' => '🇸🇪', 'name' => 'Sweden'],
            'CH' => ['flag' => '🇨🇭', 'name' => 'Switzerland'],
            'UA' => ['flag' => '🇺🇦', 'name' => 'Ukraine'],
            'GB' => ['flag' => '🇬🇧', 'name' => 'United Kingdom'],
            'VA' => ['flag' => '🇻🇦', 'name' => 'Vatican City'],
            // Africa
            'DZ' => ['flag' => '🇩🇿', 'name' => 'Algeria'],
            'AO' => ['flag' => '🇦🇴', 'name' => 'Angola'],
            'CM' => ['flag' => '🇨🇲', 'name' => 'Cameroon'],
            'CD' => ['flag' => '🇨🇩', 'name' => 'DR Congo'],
            'ET' => ['flag' => '🇪🇹', 'name' => 'Ethiopia'],
            'GH' => ['flag' => '🇬🇭', 'name' => 'Ghana'],
            'CI' => ['flag' => '🇨🇮', 'name' => 'Ivory Coast'],
            'KE' => ['flag' => '🇰🇪', 'name' => 'Kenya'],
            'LY' => ['flag' => '🇱🇾', 'name' => 'Libya'],
            'MG' => ['flag' => '🇲🇬', 'name' => 'Madagascar'],
            'MW' => ['flag' => '🇲🇼', 'name' => 'Malawi'],
            'ML' => ['flag' => '🇲🇱', 'name' => 'Mali'],
            'MA' => ['flag' => '🇲🇦', 'name' => 'Morocco'],
            'MZ' => ['flag' => '🇲🇿', 'name' => 'Mozambique'],
            'NA' => ['flag' => '🇳🇦', 'name' => 'Namibia'],
            'NG' => ['flag' => '🇳🇬', 'name' => 'Nigeria'],
            'RW' => ['flag' => '🇷🇼', 'name' => 'Rwanda'],
            'SN' => ['flag' => '🇸🇳', 'name' => 'Senegal'],
            'ZA' => ['flag' => '🇿🇦', 'name' => 'South Africa'],
            'SD' => ['flag' => '🇸🇩', 'name' => 'Sudan'],
            'TZ' => ['flag' => '🇹🇿', 'name' => 'Tanzania'],
            'TN' => ['flag' => '🇹🇳', 'name' => 'Tunisia'],
            'UG' => ['flag' => '🇺🇬', 'name' => 'Uganda'],
            'ZM' => ['flag' => '🇿🇲', 'name' => 'Zambia'],
            'ZW' => ['flag' => '🇿🇼', 'name' => 'Zimbabwe'],
            // Americas
            'AR' => ['flag' => '🇦🇷', 'name' => 'Argentina'],
            'BO' => ['flag' => '🇧🇴', 'name' => 'Bolivia'],
            'BR' => ['flag' => '🇧🇷', 'name' => 'Brazil'],
            'CA' => ['flag' => '🇨🇦', 'name' => 'Canada'],
            'CL' => ['flag' => '🇨🇱', 'name' => 'Chile'],
            'CO' => ['flag' => '🇨🇴', 'name' => 'Colombia'],
            'CR' => ['flag' => '🇨🇷', 'name' => 'Costa Rica'],
            'CU' => ['flag' => '🇨🇺', 'name' => 'Cuba'],
            'DO' => ['flag' => '🇩🇴', 'name' => 'Dominican Republic'],
            'EC' => ['flag' => '🇪🇨', 'name' => 'Ecuador'],
            'SV' => ['flag' => '🇸🇻', 'name' => 'El Salvador'],
            'GT' => ['flag' => '🇬🇹', 'name' => 'Guatemala'],
            'HT' => ['flag' => '🇭🇹', 'name' => 'Haiti'],
            'HN' => ['flag' => '🇭🇳', 'name' => 'Honduras'],
            'JM' => ['flag' => '🇯🇲', 'name' => 'Jamaica'],
            'MX' => ['flag' => '🇲🇽', 'name' => 'Mexico'],
            'NI' => ['flag' => '🇳🇮', 'name' => 'Nicaragua'],
            'PA' => ['flag' => '🇵🇦', 'name' => 'Panama'],
            'PY' => ['flag' => '🇵🇾', 'name' => 'Paraguay'],
            'PE' => ['flag' => '🇵🇪', 'name' => 'Peru'],
            'PR' => ['flag' => '🇵🇷', 'name' => 'Puerto Rico'],
            'TT' => ['flag' => '🇹🇹', 'name' => 'Trinidad & Tobago'],
            'US' => ['flag' => '🇺🇸', 'name' => 'United States'],
            'UY' => ['flag' => '🇺🇾', 'name' => 'Uruguay'],
            'VE' => ['flag' => '🇻🇪', 'name' => 'Venezuela'],
            // Oceania
            'AU' => ['flag' => '🇦🇺', 'name' => 'Australia'],
            'FJ' => ['flag' => '🇫🇯', 'name' => 'Fiji'],
            'NZ' => ['flag' => '🇳🇿', 'name' => 'New Zealand'],
            'PG' => ['flag' => '🇵🇬', 'name' => 'Papua New Guinea'],
            'WS' => ['flag' => '🇼🇸', 'name' => 'Samoa'],
        ];
    }

    // Get just name with flag for display
    public static function label(string $code): string
    {
        $countries = self::all();
        if (isset($countries[$code])) {
            return $countries[$code]['flag'] . ' ' . $countries[$code]['name'];
        }
        return $code;
    }
}
